version: "3.7"
services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
  api:
    build: .
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
  web:
    build: ./react-app
    depends_on:
      - api
    ports:
      - 3000:3000
    volumes:
      - './react-app:/usr/src/app'
      - '/usr/src/app/node_modules'
    stdin_open: true