version: "3.7"
services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
  web:
    build: .
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - ./:/var/www/html